import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Code2, LogIn, LogOut, UserPlus } from 'lucide-react'
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <header className="px-4 lg:px-6 h-14 flex items-center">
          <Link className="flex items-center justify-center" href="/">
            <Code2 className="h-6 w-6" />
            <span className="ml-2 text-lg font-bold">DevJourney</span>
          </Link>
          <nav className="ml-auto flex gap-4 sm:gap-6">
            <Link className="text-sm font-medium hover:underline underline-offset-4" href="/problems">
              Problems
            </Link>
            <Link className="text-sm font-medium hover:underline underline-offset-4" href="/learn">
              Learn
            </Link>
            <Link className="text-sm font-medium hover:underline underline-offset-4" href="/compete">
              Compete
            </Link>
            <Link className="text-sm font-medium hover:underline underline-offset-4" href="/challenge">
              Challenge
            </Link>
            <Link className="text-sm font-medium hover:underline underline-offset-4" href="/jobs">
              Jobs
            </Link>
            {true && (
              <Link className="text-sm font-medium hover:underline underline-offset-4" href="/dashboard">
                Dashboard
              </Link>
            )}
          </nav>
          {false ? (
            <Button 
              variant="ghost" 
              className="ml-4" 
             
            >
              <LogOut className="h-4 w-4 mr-2" />
              Logout
            </Button>
          ) : (
            <div className="ml-4 flex gap-2">
              <Button 
                variant="ghost" 
              
              >
                <LogIn className="h-4 w-4 mr-2" />
                Login
              </Button>
              <Button 
                variant="ghost" 
                
              >
                <UserPlus className="h-4 w-4 mr-2" />
                Register
              </Button>
            </div>
          )}
       
        </header>
        
        <main>{children}</main>
        <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
          <p className="text-xs text-gray-500 dark:text-gray-400">
            © 2025 DevJourney. All rights reserved.
          </p>
          <nav className="sm:ml-auto flex gap-4 sm:gap-6">
            <Link className="text-xs hover:underline underline-offset-4" href="#">
              Terms of Service
            </Link>
            <Link className="text-xs hover:underline underline-offset-4" href="#">
              Privacy
            </Link>
            <Link className="text-xs hover:underline underline-offset-4" href="#">
              About
            </Link>
            <Link className="text-xs hover:underline underline-offset-4" href="#">
              Contact
            </Link>
          </nav>
        </footer>
      </body>
    </html>
  )
}