name: Streak Reset Job

on:
  schedule:
    - cron: "31 18 * * *"  
  workflow_dispatch:  

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Call Next.js API to Send Email
        run: |
          curl -X POST "https://dev-journey-alpha.vercel.app/api/reset-streak"
